### ISSUE TITLE
NoClassDefFoundError for DispatcherThread.pollQs(DispatcherThread.java:329)

### ISSUE THREAD

**Issue by davidwynter** [RuedigerMoeller/kontraktor#18]
Hi,

I think this might be related to the comment in DispatcherThread nr line 329. I built a black box tester producing millions of MQ messages and sometimes when it runs we get a set of hundreds of these exceptions. It suggests we need to restart that actor, I cannot identify which actor has stopped. Unfortunately it does not occur when run from the IDE. It appears to occur when we are under load, But the tool continues to produce the MQ messages so assume it must be to do with one of the many MQQueue wrapper Actors I use or a logging Actor I have. Hard to identify. It does freak out the testers though to see these messages in the log...

java.lang.NoClassDefFoundError: Could not initialize class org.nustaq.kontraktor.impl.InternalActorStoppedException
        at org.nustaq.kontraktor.impl.DispatcherThread.pollQs(DispatcherThread.java:329)
        at org.nustaq.kontraktor.impl.DispatcherThread.pollQs(DispatcherThread.java:262)
        at org.nustaq.kontraktor.impl.DispatcherThread.run(DispatcherThread.java:162)

**Comment by RuedigerMoeller** [comment]
1. I need some context :)
2. do you use the latest version ?

**Comment by davidwynter** [comment]
I had been using V3.10. But switched to the 3.12 version yesterday and realised that with the blocking call to the MQQueue object when I call their put method I should really be using the exec() method inside a static class. So I tried this but I get very weird behaviour. The Debug view in Eclipse goes nuts unable to keep up with the changing instances and the app terminates before completing any work inside the SendQueue.sendMsg.

Here is an extract of the code 

```
...
    public void sendMsg(QueueMessage msg) {
    sender.sendMsg(msg, queue, queueName);
}

public static class SendQueue extends Actor<SendQueue> {

    long recvMsg = 0l;
    final MQPutMessageOptions pmo = new MQPutMessageOptions();

    public void sendMsg(final QueueMessage msg, final MQQueue queue,
            final String queueName) {
        Promise promise = new Promise<>();
        exec(new Callable<Object>() {
            @Override
            public Object call() throws Exception {
                                   ...
                                   queue.put(requestMsg, pmo);
                                   ...
                                    return requestMsg;
            }
        }).then(promise);
    }
}
```

Cannot explain why this occurs, maybe you can enlighten me? I had a configurable number of the actors that enclose the static SendQueue class and call then in a round robin fashion. But to debug I reduced this to a single instance of this actor, no round robin calling, and still get this weird behaviour. I modelled my implementation on your TicketMachineTest case. The other test cases seem to use a exec() without the Callable arg and I do not see that supported by Actor class?

**Comment by davidwynter** [comment]
Next week hope to get a chance to put together a small application that reproduces this issue and post the code here.

**Comment by RuedigerMoeller** [comment]
Do you use remoting ?

I looks like the root issue is, that you are trying to send messages to a stopped actor. Cannot explain the instantiation failer, though.

**General Advice**

A common source of issues with kontraktor currently are the fixed-sized, blocking queues. Once a queue is full, it backpressures to the sender by not accepting new messages which frequently leads to very unpredictable application behaviour. In case of remoting using sync TCP, this can lead to connection loss.

A simple check is to just increase the queue sizes (e.g. by just raising SimpleScheduler.DEFQSIZE to say 256_000 or even higher) and see if the problem persists.

I plan on giving up bounded queues in the near future as it turns out its a permanent root of issues, confusion and even worse: it often happens under production load first.

**Comment by RuedigerMoeller** [comment]
version 3.16 defaults to unbounded queues. This should fix those load related issues.
