### ISSUE TITLE
Problems with LongPolling

### ISSUE THREAD

**Issue by Inferior0** [RuedigerMoeller/kontraktor#27]
The following simple test program does not work as expected, from time to time it hangs for several seconds:
Server code:
import org.nustaq.kontraktor.Actor;
import org.nustaq.kontraktor.Actors;
import org.nustaq.kontraktor.IPromise;
import org.nustaq.kontraktor.remoting.encoding.SerializerType;
import org.nustaq.kontraktor.remoting.http.HttpPublisher;
import org.nustaq.kontraktor.remoting.tcp.TCPNIOPublisher;
import org.nustaq.kontraktor.remoting.websockets.WebSocketPublisher;
import org.nustaq.kontraktor.util.Log;

public class TestServer extends Actor<TestServer> {

```
public static void main(String[] args) {
    TestServer wg = Actors.AsActor(TestServer.class);
```

//        new WebSocketPublisher().facade(wg).hostName("localhost").urlPath("/testws").port(8080).serType(SerializerType.FSTSer).publish(null);
//        new TCPNIOPublisher().facade(wg).port(8080).serType(SerializerType.FSTSer).publish(null);
        new HttpPublisher().facade(wg).hostName("localhost").urlPath("/testhttp").port(8080).serType(SerializerType.FSTSer).publish(null);
    }

```
public IPromise<String> test(String test) {
    Log.Info(this, " test: " + test);
    return resolve(test + " Result");
}
```

}

Client code:
import java.util.concurrent.atomic.AtomicInteger;

import org.nustaq.kontraktor.Actor;
import org.nustaq.kontraktor.IPromise;
import org.nustaq.kontraktor.Promise;
import org.nustaq.kontraktor.impl.SimpleScheduler;
import org.nustaq.kontraktor.remoting.base.ConnectableActor;
import org.nustaq.kontraktor.remoting.encoding.SerializerType;
import org.nustaq.kontraktor.remoting.http.HttpConnectable;
import org.nustaq.kontraktor.remoting.tcp.TCPConnectable;
import org.nustaq.kontraktor.remoting.websockets.WebSocketConnectable;
import org.nustaq.kontraktor.util.Log;

public class TestClient extends Actor<TestClient> {

```
private final int ITERATIONS = 1000;

public static void main(String[] args) {
    Log.Lg.setSeverity(Log.DEBUG);
    TestClient tc = new TestClient();
    IPromise<Void> res = new Promise<>();
    SimpleScheduler scheduler = new SimpleScheduler(true);
    scheduler.assignDispatcher(0).setName("TESTCLIENT");
    tc.startTest(res, scheduler).then((r, e) -> {
        Log.Info("", " trigger exit...");
        new Thread(() -> {
            Log.Info("", " exit now...");
            System.exit(0);
        }).start();
    });
}

static AtomicInteger count = new AtomicInteger();

public IPromise<Void> startTest(IPromise<Void> res, SimpleScheduler scheduler) {
    int c;
    if ((c = count.incrementAndGet()) < ITERATIONS) {
        TestClient cl = TestClient.AsActor(TestClient.class, scheduler);
        cl.test(c).then(() -> {
            cl.stopSafeClose();
            startTest(res, scheduler);
        });
    } else {
        res.resolve(null);
    }
    return res;
}

private IPromise<Void> test(int c) {
    IPromise<Void> res = new Promise<>();
    init().then(() -> {
        Log.Info(this, " CONNECT-" + c);
        connect().then((r, e) -> {
            if (r instanceof TestServer) {
                Log.Info(this, " WG_CONNECTED-" + c);
                TestServer wg = (TestServer) r;
                wg.getCurrentDispatcher().setName("WEBGATE-" + c);
                wg.test("testMsg-" + c).then((r1, e1) -> {
                    Log.Info(this, " RES=" + r1 + " ERR=" + e1);
                    Log.Info(this, " CLOSE-" + c);
                    wg.close();
                    res.resolve(null);
                });
            } else {
                Log.Info(this, "connectFailed " + c);
                res.reject(e);
            }
        });
    });
    return res;
}

public IPromise<Void> init() {
    return resolve(null);
}

public IPromise connect() {
    IPromise res = new Promise();
```

//         ConnectableActor connectable = new WebSocketConnectable(TestServer.class, "http://localhost:8080/testws").serType(SerializerType.FSTSer);
        // ConnectableActor connectable = new TCPConnectable(TestServer.class, "localhost", 8080).serType(SerializerType.FSTSer);
        ConnectableActor connectable = new HttpConnectable(TestServer.class, "http://localhost:8080/testhttp").serType(SerializerType.FSTSer);
        connectable.connect(null, null).then(res);
        return res;
    }
}

**Comment by RuedigerMoeller** [comment]
lieber inferior. paste doch mal deinen fix wenn Du das mit dem branschen nicht auf die Reihe kriegst ;) ..
