### ISSUE TITLE
StackOverflowError in HttpApp

### ISSUE THREAD

**Issue by davidwynter** [RuedigerMoeller/kontraktor#29]
**By eliminating all inner classes in my parameters passed in messages I eliminated the following StackOverflowError**

I upgraded to V3.24 after experiencing the same exception in V3.21, it is still there. 

This is a clone of the http-ws-javascript example. I am running a test from my equivalent to MyJavaClient.

The code looks like this: (no idea why the code markers do not work)

`private static void testHappyPath(ExampleHttpApp remoteApp) {
        // newUser first            
       ExampleHttpAppSession session = remoteApp.newUser("marg@hotmail.com", "alrh9c", 
                "15/12/1969", "Marg", "G", "Grasmick", 1, "answer").await();
        // Then identity, user, password, List of Address
        List<Address> addresses = new ArrayList<Address>();
        InteractiveQuery iq = session.identity("marg@hotmail.com", "alrh9c", addresses).await();
`

The stackoverflow happens on the identity call.

`    ExampleMain [Java Application] 
    uk.co.example.quokka.ExampleMain at localhost:39436 
        Thread [Timer-0](Running)  
        Thread [ExampleHttpApp Dispatcher](Suspended %28exception StackOverflowError%29)  
            FSTObjectOutput.writeObjectWithContext(FSTClazzInfo$FSTFieldInfo, Object, FSTClazzInfo) line: 462  
            FSTObjectOutput.writeObjectWithContext(FSTClazzInfo$FSTFieldInfo, Object) line: 361 
            FSTObjectOutput.writeObjectFields(Object, FSTClazzInfo, FSTClazzInfo$FSTFieldInfo[], int, int) line: 639  
            FSTObjectOutput.defaultWriteObject(Object, FSTClazzInfo) line: 526  
            FSTObjectOutput.writeObjectWithContext(FSTClazzInfo$FSTFieldInfo, Object, FSTClazzInfo) line: 446  
            FSTObjectOutput.writeObjectWithContext(FSTClazzInfo$FSTFieldInfo, Object) line: 361 
            FSTObjectOutput.writeObjectFields(Object, FSTClazzInfo, FSTClazzInfo$FSTFieldInfo[], int, int) line: 639  
            FSTObjectOutput.defaultWriteObject(Object, FSTClazzInfo) line: 526  
            FSTObjectOutput.writeObjectWithContext(FSTClazzInfo$FSTFieldInfo, Object, FSTClazzInfo) line: 446  
            FSTObjectOutput.writeObjectWithContext(FSTClazzInfo$FSTFieldInfo, Object) line: 361 
            FSTObjectOutput.writeObjectFields(Object, FSTClazzInfo, FSTClazzInfo$FSTFieldInfo[], int, int) line: 639  
            FSTObjectOutput.defaultWriteObject(Object, FSTClazzInfo) line: 526  
            FSTObjectOutput.writeObjectWithContext(FSTClazzInfo$FSTFieldInfo, Object, FSTClazzInfo) line: 446  
            FSTObjectOutput.writeObjectWithContext(FSTClazzInfo$FSTFieldInfo, Object) line: 361 
            FSTObjectOutput.writeObjectFields(Object, FSTClazzInfo, FSTClazzInfo$FSTFieldInfo[], int, int) line: 639  
            FSTObjectOutput.defaultWriteObject(Object, FSTClazzInfo) line: 526  
            FSTObjectOutput.writeObjectWithContext(FSTClazzInfo$FSTFieldInfo, Object, FSTClazzInfo) line: 446  
    ... repeat
            FSTObjectOutput.writeObjectWithContext(FSTClazzInfo$FSTFieldInfo, Object) line: 361 
            FSTObjectOutput.writeObjectFields(Object, FSTClazzInfo, FSTClazzInfo$FSTFieldInfo[], int, int) line: 639  
            FSTObjectOutput.defaultWriteObject(Object, FSTClazzInfo) line: 526  
            FSTObjectOutput.writeObjectWithContext(FSTClazzInfo$FSTFieldInfo, Object, FSTClazzInfo) line: 446  
            FSTObjectOutput.writeArray(FSTClazzInfo$FSTFieldInfo, Object) line: 775 
            FSTObjectOutput.writeObjectWithContext(FSTClazzInfo$FSTFieldInfo, Object, FSTClazzInfo) line: 419  
            FSTObjectOutput.writeObjectWithContext(FSTClazzInfo$FSTFieldInfo, Object) line: 361 
            FSTObjectOutput.writeObjectFields(Object, FSTClazzInfo, FSTClazzInfo$FSTFieldInfo[], int, int) line: 639  
            FSTObjectOutput.defaultWriteObject(Object, FSTClazzInfo) line: 526  
            FSTObjectOutput.writeObjectWithContext(FSTClazzInfo$FSTFieldInfo, Object, FSTClazzInfo) line: 446  
            FSTObjectOutput.writeArray(FSTClazzInfo$FSTFieldInfo, Object) line: 775 
            FSTObjectOutput.writeObjectWithContext(FSTClazzInfo$FSTFieldInfo, Object, FSTClazzInfo) line: 419  
            FSTObjectOutput.writeObjectInternal(Object, FSTClazzInfo, Class...) line: 319  
            FSTObjectOutput.writeObject(Object, Class...) line: 275 
            FSTObjectOutput.writeObject(Object) line: 193  
            FSTConfiguration.asByteArray(Object) line: 1125 
            UndertowWebsocketServerConnector$UTWebObjectSocket(WebObjectSocket).flush() line: 80  
            ActorServer$2(RemoteRegistry).pollAndSend2Remote(AtomicReference<ObjectSocket>) line: 551  
            RemoteRefPolling.onePoll() line: 132  
            RemoteRefPolling.run() line: 90 
            NativeMethodAccessorImpl.invoke0(Method, Object, Object[]) line: not available [native method]  
            NativeMethodAccessorImpl.invoke(Object, Object[]) line: 62  
            DelegatingMethodAccessorImpl.invoke(Object, Object[]) line: 43  
            Method.invoke(Object, Object...) line: 498  
            DispatcherThread.invoke(CallEntry) line: 366  
            DispatcherThread.pollQs(Actor[], int) line: 289 
            DispatcherThread.pollQs() line: 262 
            DispatcherThread.run() line: 162    

`

If it is not obvious what the problem is I will build a extended version of the example app that produces the same issue.

**Comment by RuedigerMoeller** [comment]
hm .. overuse of await can trigger a stackoverflow, do not use await inside the main path of your server. In addition it happened that very complex objectgraphs triggered a stacloverflow.
A common issue is to accidentally serialize outer classes by referencing enclosing class fields inside a lambda or anonymous

**Comment by davidwynter** [comment]
Thx Ruediger, It was the await() that caused problems. I replaced all my await methods with Lambda expressions and the tests all passed.

A quick question I see that I have a very large structure in a response, the actual data makes up maybe 25% at most, most of it is labels, e.g. a part of it:

`{"typ":"uk.co.example.quokka.domain.CardStatus","obj":{"balance":6052,"limit":10293,"status":0,"paymentDate":1465996186018,"statementDate":1464786586018}},`

I use FST too, and it allows you to register classes, can we do something similar for over the wire too?

Thx again
