### ISSUE TITLE
Cancellation? (Docs)

### ISSUE THREAD

**Issue by Petikoch** [RuedigerMoeller/kontraktor#31]
Hi @RuedigerMoeller,

congratulations for your work! 

I have a question regarding cancellation with kontraktor. I didn't find anything to this in https://github.com/RuedigerMoeller/kontraktor/wiki/Kontraktor-3 or on the IPromise API.

How do I cancel an ongoing async operation?

Since this is a standard use-case for me, it would be nice to have something about it in the docs.

Best regards from Switzerland,
Peti

**Comment by RuedigerMoeller** [comment]
This could be achieved implementing a simple wrapper which simply ignores a callback in case of cancellation. As kontraktor's promises are potentially remoted, there is no "real" cancellation, just ignorance of an incoming result.

``` java
    public static class CancelablePromise<T> extends Promise<T> {
        volatile boolean cancelled;

        public CancelablePromise(IPromise<T> original) {
            original.then( (r,e) -> {
                if ( ! cancelled ) {
                    complete(r,e);
                }
            });
        }

        public void cancel() {
            cancelled = true;
        }
    }
```

you might use this like

``` java
CancelablePromise myP = new CancelablePromise( actor.asyncMethod() );
myP.then( r -> System.out.println(r) );
```

note this is an ad-hoch example, but it should work along the lines of this.

**Comment by Petikoch** [comment]
Thanks very much for the response.

This wasn't the answer I hoped for. For me "real" cancellation - also for a remote async operation - is a key feature. 

E.g. in Hazelcast I have the "distributed ExecutorService" with a working `Future#cancel`: http://docs.hazelcast.org/docs/3.7/manual/html-single/index.html#canceling-an-executing-task

Best regards,
Peti

**Comment by RuedigerMoeller** [comment]
Providing this on a default level would be way too heavyweight. A promise in kontraktor is much more lightweight to what you describe. Most remote methods execute way too fast, so a cancellation would be way too late (network latency > remote method runtime). So for rare cases like e.g. a remote executor service such behavior can be built from lightwight primitives with a few lines of code.
