### ISSUE TITLE
Websocket interface stops working once Kontraktor is in a docker image

### ISSUE THREAD

**Issue by davidwynter** [RuedigerMoeller/kontraktor#36]
This may not have anything to do with Kontraktor and how it supports websockets, but it is worth investigating as my other enquiries are not proving fruitful. See the question here:

http://stackoverflow.com/questions/41383510/websocket-not-attaching-into-docker-container

I tried HTLP as well and got a timeout. Given the error with websockets suggests it makes connection, then gets dropped I will use the http example and package that in docker to see if I can reproduce.

**Comment by RuedigerMoeller** [comment]
http long poll connector has lower throughput. are you talking of javascript <=> server or cluster-node to cluster-node connector ?

**Comment by RuedigerMoeller** [comment]
on a second note, there are many reports (from real devs, not geek-porn style media) complaining with overall stability of docker, so maybe not the best choice for deploying apps ..

https://thehftguy.com/2016/11/01/docker-in-production-an-history-of-failure/

**Comment by davidwynter** [comment]
With the difficulty in debugging these container issues and the fact your link convinced me not to use Docker I am abandoning it's use. That article lead me to discover that overlay, Docker storage drivers do not support any encrypted filesystems, a show  stopper for me. I'll look at Go by Thoughtworks to see if I can automate the deployment so well I just need a lightweight Linux OS to run on top of.

**Comment by RuedigerMoeller** [comment]
I am running my stuff in private clouds (fixed real servers) and use NFS, and peer-to-peer "https://github.com/RuedigerMoeller/kontraktor/tree/trunk/modules/kluster-troll" which basically uses the java process api to manage distributed groups of processes. quite low tec but works like a charm ;). Which cloud product do you run on ?

**Comment by davidwynter** [comment]
I have used both Digital Ocean and OVH. The former has great self help articles and the latter unbeatable prices. But, we have to go for ISO 27001:2013 and it looks like the easiest way to do this is get dedicated servers from OVH.com I will probably start with 2 machines, each will run our webapp and the 5 services that provide interfaces to external services or independent function such as our lightweight CMS. Probably using OVH's load balancing service on the front. A lot depends on whether we can use on demand cloud infrastructure (ISO 27001 issue potentially) to cope with usage spikes dynamically. I'd like to be able to automatically spin up a VM and deploy a full working app stack to it in a short timeframe, kluster-troll might be useful here.
