### ISSUE TITLE
How to debug "unable to decode" errors

### ISSUE THREAD

**Issue by davidwynter** [RuedigerMoeller/kontraktor#38]
I have lots of remote actors that work just fine. But 1 is not working and I cannot see what the problem is. 

Here is the test case 

	@BeforeClass
    public static void init() {
		JSR356ClientConnector.DumpProtocol = true; // dev only
		remoteApp = (EquifaxAddrService) new WebSocketConnectable(EquifaxAddrService.class, 
				"ws://localhost:49003/addr")
				.serType(SerializerType.JsonNoRefPretty).connect().await();

    }

    /**
     * Basic Test
     */
    @Test
    public void testAddressList()
    {
		remoteApp.addressList("", "BA133BN").then((res, err) -> {
			for(String desc: res.getAddrDesc()) {
				logger.info(desc);
				assertTrue( res.getAddrDesc().size() > 0);
			}
			for(String pctabs : res.getPctabs()) {
				logger.info(pctabs);
				assertTrue( res.getPctabs().size() > 0);
			}
		}).onTimeout(to -> {
			fail("Timeout");
		}).catchError(err -> {
			fail("Error returned - " + err);
		});
        
    }

Here is the remoteApp.addressList signature

	public IPromise<AddrList> addressList(String houseNameNo, String postcode) {

Here is the dumped output from the Actor

    unable to decode:{
      "styp" : "array",
      "seq" : [ 2, {
         "typ" : "call",
         "obj" : {
           "queue" : 0,
           "futureKey" : 1,
           "receiverKey" : 1,
           "args" : {
             "styp" : "array",
             "seq" : [ 2, "", "BA133BN" ]
           },
           "method" : "addressList"
         }
       }, 1 ]
     } 

Is there a way of getting more information on why it is unable to decode? #

**Comment by RuedigerMoeller** [comment]
hm, this looks quite standard, will check tomorrow. actually the fst parser mostly has no clue why parsing failed ;), so there is this "something went wrong" message. maybe its some other exception during method dispatch which then falls through and is treated as decoding error

**Comment by davidwynter** [comment]
I solved this, it was obvious in the end. I had mismatched the serializers.
