### ISSUE TITLE
JSON decode error in js4k.js with 3.32

### ISSUE THREAD

**Issue by davidwynter** [RuedigerMoeller/kontraktor#40]
I am getting this error using 3.32:

    GET 
    http://localhost:8080/ws [HTTP/1.1 101 Switching Protocols 8ms]
    Connection successful  testwebsocket.html:16:17
    unhandled decoding error:TypeError: resp.obj.args is null  js4k.js:577:17
	_jsk.KontraktorSocket/self.onmessage/self.socket.onmessage/parse/fr.onloadend file:///Users/david/creditswift/creditswift/web/app/js/js4k.js:577:17
    TypeError: resp.obj.args is null
    Stack trace:
    processSocketResponse@file:///Users/david/creditswift/creditswift/web/app/js/js4k.js:468:17
    _jsk.KontraktorSocket/self.onmessage/self.socket.onmessage/parse/fr.onloadend@file:///Users/david/creditswift/creditswift/web/app/js/js4k.js:575:17
    testwebsocket.html:6:33
	errCB file:///Users/david/creditswift/creditswift/web/testwebsocket.html:6:33
	_jsk.connect/< file:///Users/david/creditswift/creditswift/web/app/js/js4k.js:244:9
	_jsk.KontraktorSocket/self.onmessage/self.socket.onmessage/parse/fr.onloadend file:///Users/david/creditswift/creditswift/web/app/js/js4k.js:579:19

I made sure js4k.js was copied from my 3.32 checked out Kontraktor. 

I reverted to 3.28 and it works.

Here is the calling code:

		var server = null;
		var errCB = function( err ) { console.error(err); };
		
		console.log('Starting');
		
        jsk.connect("ws://localhost:8080/ws", "WS", errCB)
            .then(function(app, err) {
                if (!app) {
                    console.log("Error establishing websocket connection");
                    console.error(err);   
                }
                console.log('Connection successful');
                server = app;
                server.ask('login', "JAMES.TAYLOR@yahoo.com", "*******").then(function(session, err) {
                    if (err) {
                        console.error(err);
                    } else {
                    	console.log(session);

**Comment by davidwynter** [comment]
I see you did a later 3.32 version and a new 3.33 version. I tried the latter but now one of my services uses the quartz scheduler, which of course uses slf4j and despite excluding log4j and slf4j from the quartz dependencies in the pom.xml it still loads a version of the StaticLoggerBinder that does not have the required getLoggerFactoryClassStr method. I can only assume despite what the dependency:tree says maven does not work as specified on occasion. So will have to stick with 3.28

**Comment by RuedigerMoeller** [comment]
I'll add the missing method in 3.34 (forgot, sorry). 3.33 seems should be stable again (requires update of js4k.js)

**Comment by davidwynter** [comment]
Ha, hadn't checked it was in 3.33.... My error

**Comment by RuedigerMoeller** [comment]
i updated kontraktor-http to 3.33.1 on maven.org (should be public in some hours). 3.33.1 contains the method you requested on StaticLoggerBinder

**Comment by RuedigerMoeller** [comment]
arg .. I did not test websockets .. probably destroyed them with my changes .. will fix asap

**Comment by RuedigerMoeller** [comment]
i checked back, apparently your js4k is not up to date. I started making changes to 3.32, then branched half way leaving the trunk version in an invalid state and merged back the branch to 'trunk', you might have taken an invalid version of js4k meanwhile.

I tested websockets example (see repo) with 3.33 (kontraktor http: 3.33.1) and the js4k 3.33 and it worked correctly. The line number of your example does not match my version.

In case I missed something: resp.obj.args are null initially but resp.obj.serializedArgs contains jsonized arguments. So something like this
```javascript
          if ( resp.obj.serializedArgs ) {
            resp.obj.args = JSON.parse(resp.obj.serializedArgs);
            resp.obj.serializedArgs = null;
          }
```
is required before accessing a responses arguments.

**Comment by davidwynter** [comment]
I updated to 3.33, all is good, at least running on localhost in dev. I deployed to my VM in the cloud and get a couple of errors. Also get this when I package and run from jar files locally, so might be a packaging issue. Not sure how to debug these, because none of my classes are in the stack trace. Do you have any guidance?

    I 08:30:10:393 : ExampleHttpApp Dispatcher : ActorServer : connected a client with registry 1670426013
    E 08:30:10:499 : XNIO-1 I/O-2 :  : null
    java.lang.StringIndexOutOfBoundsException: String index out of range: 100
	at java.lang.String.checkBounds(String.java:385)
	at java.lang.String.<init>(String.java:324)
	at org.nustaq.serialization.FSTConfiguration.asObject(FSTConfiguration.java:1109)
	at org.nustaq.kontraktor.remoting.encoding.RemoteCallEntry.unpackArgs(RemoteCallEntry.java:138)
	at org.nustaq.kontraktor.Actor.__dispatchRemoteCall(Actor.java:622)
	at org.nustaq.kontraktor.remoting.base.RemoteRegistry.processRemoteCallEntry(RemoteRegistry.java:344)
	at org.nustaq.kontraktor.remoting.base.RemoteRegistry.receiveObject(RemoteRegistry.java:303)
	at org.nustaq.kontraktor.remoting.base.ActorServer$3.receiveObject(ActorServer.java:107)
	at org.nustaq.kontraktor.remoting.base.ObjectSink.receiveObject(ObjectSink.java:38)
	at org.nustaq.kontraktor.remoting.websockets.UndertowWebsocketServerConnector$1.onFullTextMessage(UndertowWebsocketServerConnector.java:99)
	at io.undertow.websockets.core.AbstractReceiveListener$2.complete(AbstractReceiveListener.java:156)
	at io.undertow.websockets.core.AbstractReceiveListener$2.complete(AbstractReceiveListener.java:152)
	at io.undertow.websockets.core.BufferedTextMessage.read(BufferedTextMessage.java:105)
	at io.undertow.websockets.core.AbstractReceiveListener.readBufferedText(AbstractReceiveListener.java:152)
	at io.undertow.websockets.core.AbstractReceiveListener.bufferFullMessage(AbstractReceiveListener.java:90)
	at io.undertow.websockets.core.AbstractReceiveListener.onText(AbstractReceiveListener.java:70)
	at io.undertow.websockets.core.AbstractReceiveListener.handleEvent(AbstractReceiveListener.java:44)
	at io.undertow.websockets.core.AbstractReceiveListener.handleEvent(AbstractReceiveListener.java:33)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:775)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:763)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:539)

This occurs after I get the HttpSession object back, same javascript as above, at 

    "server.ask('login'".

**Comment by RuedigerMoeller** [comment]
This is a decoding error. The "outofrange" happens because of an errornous diagnostic statement in FSTConfiguration.asObject

```java
public Object asObject( byte b[] ) {
        try {
            return getObjectInput(b).readObject();
        } catch (Exception e) {
            System.out.println("unable to decode:" +new String(b,0,0,Math.min(b.length,100)) );
            try {
                String debug = new String(b, "UTF-8");
            } catch (UnsupportedEncodingException e1) {
                //
            }
            try {
                getObjectInput(b).readObject();
            } catch (Exception e1) {
                // debug hook
            }
            FSTUtil.<RuntimeException>rethrow(e);
        }
        return null;
    }
```

our system runs fine with 3.33, so its probably something specific to your setup (maybe jar hell or specific encoding setup, note fst 2.44.5 is used in 3.33. The deployment platform should not make a difference ?

out setup:
18 nodes talking to each other via TCP/FSTSerialization,
2 WebServers talk with backend via tcp/fstbinary, Frontend js4k/JSonNoRef

In case we cannot ressolve this, I can offer you to add a branch rooting at 3.28. Actually changes done to kontraktor at this point are 100% feature/enhancement changes, not related to bug fixes as the platform already is in a quite stable & tested state. Real bugfix changes could be reconciled in the 3.28 branch then in case.

**Comment by RuedigerMoeller** [comment]
You probably have wrong version of FST ! 
2.44.5 has
`System.out.println("unable to decode:" +new String(b,0,0,Math.min(b.length,100)) );`
while older/other versions had
`System.out.println("unable to decode:" +new String(b,0,0,Math.max(b.length,100)) );`
which throws the Exception you see above in case b is shorter than 100.

**Comment by davidwynter** [comment]
You got it 1! But on updating the jar files that used FST I now get a different error. Has the encoding changed? I am using it for all my application data storage, it takes 30 minutes to regenerate due to external WS calls. Do I need to regenerate my data stores?

    W 12:23:14:357 : ExampleHttpApp Dispatcher : DispatcherThread : unhandled exception in message: 'CallEntry{method=getCSUserBundle, futureCB=org.nustaq.kontraktor.impl.CallbackWrapper@758546bb, target=uk.co.example.quokka.ExampleHttpApp@2ca154b1, sendingActor=uk.co.example.quokka.ExampleHttpAppSession@24ba20c, targetActor=uk.co.example.quokka.ExampleHttpApp@2ca154b1, onCBQueue=false}'.returned catched exception to future java.lang.RuntimeException: java.io.IOException: java.lang.RuntimeException: class not found CLASSNAME: loader:sun.misc.Launcher$AppClassLoader@6bc7c054 set DispatcherThread.DUMP_CATCHED to true in order to dump stack.
    java.lang.RuntimeException: java.io.IOException: java.lang.RuntimeException: class not found CLASSNAME: loader:sun.misc.Launcher$AppClassLoader@6bc7c054
	    at org.nustaq.offheap.FSTCodedOffheapMap.get(FSTCodedOffheapMap.java:63)
	    at uk.co.example.quokka.ExampleDataService.getDemousers(ExampleDataService.java:265)

**Comment by RuedigerMoeller** [comment]
Kontraktor uses its own branch of fst (2.44.X) which is kept binary stable to overcome issues with persistant serialized objects. Version issues are the downside of the convenience tradeoff regarding serilaization.
If you used fst >2.44 (e.g. 2.48) you probably need to convert your data, else it should not make a difference (actually parts of our production data has been created with 2.44.1 and is still readable with 2.44.5). 

Just in case: if you have a huge dataset of serialized objects and need to recode to a incompatible version of FST there is the option to convert data by package renaming fst and use 2 versions of fst during conversion in a single VM.

**Comment by RuedigerMoeller** [comment]
class not found "FSTCodedOffheapMap" - must be a build error this class has been there for ages

**Comment by davidwynter** [comment]
I have removed the FST dependency from my pom.xml, will rely on the one included with kontraktor, much safer. 

Reading other earlier issue with FST I see it is not "FSTCodedOffheapMap" that is missing, it looks like it is an unknown class being read from the mmf file. I'll investigate further by using some FST debug statements to console.

**Comment by davidwynter** [comment]
Looks like I have to abandon the use of FST for my key value data store. I tried 3 different ways of packaging my app, maven-shade, maven-assembly and finally maven-dependency plugins. It is not a class loading issue. Using remote debugging allowed me to trace into FST, but for some reason I get "unable to resolve binding: .." on all variables I see in the trace into FST. So no clue why it is failing. Runs perfectly with the same code and same mmf files when running under Eclipse in dev.
