### ISSUE TITLE
How to build kontraktor components without Maven cyclic dependencies

### ISSUE THREAD

**Issue by davidwynter** [RuedigerMoeller/kontraktor#41]
This is a question about the best way to arrange your Maven projects where you have several Kontraktor Actors messaging each other. The Actors need to include each other in their pom.xml which causes cyclic dependencies and breaks the build. What is the best approach for this? I could create a project with just interfaces for all Actors that communicate with each other and include that in all of those Actor components?

**Comment by davidwynter** [comment]
Looking into this the only way I can solve this is include all Actors that message each other into a parent project and have all the service supporting code (mostly generated web service code) for each Actor in a child project. This aligns with what you do with for Eurex.

**Comment by RuedigerMoeller** [comment]
tbh as of now i always deploy a fat jar containing the full code :)
