### ISSUE TITLE
Advice on configuring for wss?

### ISSUE THREAD

**Issue by davidwynter** [RuedigerMoeller/kontraktor#45]
Hi,

I looked through the test cases for kontraktor-http and could not see any for web sockets secure (wss:// scheme). Can you offer guidance on what has to be setup? We have our key registered already.

Cheers,

David

**Comment by RuedigerMoeller** [comment]
We used nginx for that. One can configure it such that it transparently talks wss / https to the outside but ws:// and http:// to the inside. NginX configuration is somewhat tricky but manageable with help of google ;)
