### ISSUE TITLE
Kotlin Actors

### ISSUE THREAD

**Issue by mpfau** [RuedigerMoeller/kontraktor#46]
I saw that you played around with kotlin in an example. This made me interested, too and I tried to use kontraktor with kotlin. Unfortunately, sth. seems wrong with kotlin actors...

I used the same (kotlin) client for two two examples where the server (actor) part has been implemented once in Java and once in Kotlin:
* Unfortunately, the kotlin actor was executed in the client scope.
* The  Actor implemented was executed in the server scope as expected. 

I launched separate VMs for client and server in both cases.

**Comment by RuedigerMoeller** [comment]
oops, will investigate as i find time .. busy currently. actually the kotlin stuff was just some playground ..

**Comment by RuedigerMoeller** [comment]
you are right, seems like kotlin clashes with the runtime bytecode generation done by kontraktor. Same example works with java implementation ..

**Comment by RuedigerMoeller** [comment]
only tell/aks semantics schedule properly

```kotlin
        client.ask("xy", 17 ).then { x,y -> println("remote result $x" ) } // works
        client.xy( 17 ).then { x,y -> println("remote result $x" ) }  // does not work !!!!!
```

**Comment by RuedigerMoeller** [comment]
I found the issue: by default all kotlin methods are final, so the generated overridden methods did not get called. changing remoteable methods to "open" fixed it. Still somewhat whacky  ..

see updated example

**Comment by mpfau** [comment]
Great catch! Thanks! :)

Jul 31, 2017, 8:23 PM by notifications@github.com:
