### ISSUE TITLE
Associating a file upload with a Session

### ISSUE THREAD

**Issue by davidwynter** [RuedigerMoeller/kontraktor#71]
Any advice on how I could associate a file upload with a particular session? 

I added a file upload handler like so in the MainApp. 

`

	private void handleFileUploadRequest(HttpServerExchange exchange) {
		Builder builder = FormParserFactory.builder();

		final FormDataParser formDataParser = builder.build().createParser(exchange);
		if (formDataParser != null) {
			exchange.startBlocking();
			FormData formData;
			try {
				formData = formDataParser.parseBlocking();
				for (String data : formData) {
					for (FormData.FormValue formValue : formData.get(data)) {
						if (formValue.isFile()) {
							File upload = formValue.getPath().toFile();
							try {
				                String fileContents = new String(Files.readAllBytes(upload.toPath()), StandardCharsets.UTF_8);
				                ByteBuffer buffer = ByteBuffer.allocateDirect(fileContents.length());
				                buffer.put(fileContents.getBytes(UTF_8));
				                buffer.flip();
				                File file = new File("./images/"+formValue.getFileName());
				                try (FileChannel wChannel = new FileOutputStream(file, false).getChannel()) {
					                wChannel.write(buffer);
				                }
				            } catch (IOException e) {
				                logger.debug("File upload failed during file handling with - ", e.getMessage());
				            }
				        }
					}
				}
			} catch (IOException e1) {
                logger.debug("File upload failed during Http handling with - ", e1.getMessage());
			}
		}
	}
`

with the entry point here:

`

    Http4K.Build(address, port)

    .httpHandler("/upload", exchange -> {
				exchange.dispatch();
				app.self().handleFileUploadRequest(exchange);
			})

    .httpHandler( "/images", exchange -> {
                exchange.dispatch();
                app.self().handleGetImageRequest(exchange);
            })

    .websocket("/ws", app).serType(SerializerType.JsonNoRef).sendSid(true).buildWebsocket().build();
`

But what I'd like to do is associate the file upload with the session the user is logged in on. Any way of doing this?

**Comment by davidwynter** [comment]
I worked out I can get the session id (a user id) added to the formdata that has the file as an attachment, then grab that in my HttpHandler to associate with the file. However I do get an exception on the line in my handler that has  `formData = formDataParser.parseBlocking();`

I get 

`java.lang.IllegalStateException: UT000126: Attempted to do blocking IO from the IO thread. This is prohibited as it may result in deadlocks
at io.undertow.io.UndertowInputStream.read(UndertowInputStream.java:84)
at io.undertow.server.handlers.form.MultiPartParserDefinition$MultiPartUploadHandler.parseBlocking(MultiPartParserDefinition.java:213)`

Not sure if this is to do with the threading model used by Kontraktor or not.

**Comment by RuedigerMoeller** [comment]
we do upload by using a method with string argument and encode the file into the String. If you place the method onto a session actor, its ensured a) proper association b) nobody can upload data without a valid login

**Comment by RuedigerMoeller** [comment]
as for your code: you are actually doing sync IO, as the handleFileupload is 'private', its not made asynchronous (only public methods are "asynchronized"). So either make it public (bad idea as you block the app's one and only thread then) or just run the whole upload thingy inside a dedicated thread (pool). E.g. use Actor::execInThreadPool.

Doing upload using a string arg worked fine for us (up to 10MB). E.g. `public IPromise uploadImage( String imgdata )` and from javascript: `session.ask( "uploadImage", base64encodedimagedata ).then( (r,e) => console.log('done')`

**Comment by RuedigerMoeller** [comment]
```javascript
onSave(){
    if( this.currentImage)
    {
      let croppedBase64 = this.getCroppedImg(this.currentImage, this.state.crop);
      Store.uploadImage(croppedBase64, 'image/jpeg').then( (result) => {
        this.setState({
          imageId: result,
        }, ()=> {
          let res = this.doValidate(result,null);
          if( this.props.onValue )
          {
            this.props.onValue(this.state.imageId,res);
          }
        });
        App.get.toastMe("Bild erfolgreich auf dem Server gespeichert.","success")
      }).catch( (error) => {
        console.error("Error upload Image:" + error );
        App.get.toastMe("Bild konnte nicht gespeichert.","error");
      });
    }

  }
```

server (inside session class):
```java
    public IPromise<String> uploadImage(String base64String , String imageType ){
        Promise<String> promise = new Promise();
        execute( ()->{
            ImageHandler handler = new ImageHandler( cfg );

            handler.handleImage(base64String,imageType,"user", new Dimension(512,512)).then( (result, error )-> {
                promise.complete(result,error);
            });
        });
        return promise;
    }
```
